import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';




export const metadata = {
  title: "Booking Appointment",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  const rtlLanguages=["ar"]
  const dir= rtlLanguages.includes(locale) ? "rtl": "ltr"
  return (
    <html lang={locale} dir={dir}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
          {/* Pass the initial hideBottomNav state to the client handler */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
