import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { cookies, headers } from 'next/headers';

import 'slick-carousel/slick/slick.css'; // Slick carousel styles
import 'slick-carousel/slick/slick-theme.css'; // Slick carousel theme styles
import BottomNavHandler from "../components/BottomNavHandler"; // Client-side handler for BottomNav

export const metadata = {
  title: "Booking Appointment",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
          {/* Pass the initial hideBottomNav state to the client handler */}
          <BottomNavHandler/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
